baseURL: /
languageCode: en-us
title: Yisu Zhou
admin: Yisu Zhou
theme: hugo-PaperMod
copyright: "&copy; Yisu Zhou"

params:
  env: production
  profileMode:
    enabled: true
    title: "Yisu Zhou" # optional default will be site title
    subtitle: "Associate Professor of Education Policy & Sociology"
    imageUrl: "./author/admin/avatar.jpg" # optional
    imageWidth: 180 # custom size
    imageHeight: 180 # custom size
    buttons:
      - name: Biography
        url: "./biography"
      - name: Translations
        url: "./translations"
      - name: Featured Publications
        url: "./publications"

  socialIcons: # optional
    - name: "twitter"
      url: "https://twitter.com/makzhou"
    - name: "googlescholar"
      url: "https://scholar.google.com/citations?user=JCyTlUIAAAAJ"
    - name: "ORCID"
      url: "https://orcid.org/0000-0001-9246-9700"
    - name: "publons"
      icon_pack: ai
      url: "https://publons.com/researcher/1619683/yisu-zhou/"
  
  homeInfoParams: 
    title: "Zhou Yisu"
    content: "Associate Professor of Education Policy & Sociology"

services:
  googleAnalytics:: 
    id: G-PSEN560TRQ

menu: 
  main: 
    - name: Biography
      url: "./biography"
      weight: 10
    - name: Publications
      url: "./publications"
      weight: 20
    - name: Courses
      url: "./courses"
      weight: 30
    - name: Translations
      url: "./translations"
      weight: 40
    - name: CV
      url: "./files/2024_yisu_cv.pdf"
      weight: 50
